openapi: '3.0.2'
info:
  title: Jatgam Wishlist API
  version: '1.0'
servers:
  - url: https://wishlist.jatgam.com/api
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
